title: "\\pkg{iNZightTools}: Tools for \\pkg{iNZight}"
authors: "Tom Elliott [1,2]"
affiliations:
  - "Te Rourou T\\=ataritanga, Victoria University of Wellington"
  - "Department of Statistics, University of Auckland"
abstract: "A package to do things."
