title: "Democratising Survey Data with iNZight"
title_short: "Democratising Survey Data with iNZight"
author: "Tom Elliott and Chris Wild and Andrew Sporle"
affiliation: "Victoria University of Auckland, University of Auckland, iNZight Analytics"
abstract: "Survey data is often full of unique and complex features that must be dealt with before the data can be analysed. This adds many additional levels of complexity to a valuable data resource. By providing a set of processes for describing complex survey designs and metadata about variables, \\inzight{}"
