title: "\\pkg{iNZight}: A Graphical User Interface for Democratising Data Visualisation, Exploration, and Analysis"
title_short: "\\pkg{iNZight}: A GUI for Democratising Data Visualisation, Exploration, and Analysis"
authors:
- "Tom Elliott [1,2]"
- "Chris Wild [2]"
- "Daniel Barnett [2]"
- "Andrew Sporle [3,2]"
affiliations:
- "Victoria University of Wellington"
- "University of Auckland"
- "iNZight Analytics"
abstract: "Visualisation, exploration, and analysis of data is often inaccessible to many due to high up-front costs of learning the necessary coding skills to get started. \\Glspl{gui} have often been used to provide inexperienced users with access to these underlying, complex systems without the need for coding. \\proglang{R} \\glspl{gui} are available, but they require some degree of experience with \\proglang{R} and a familiarity with statistical concepts. \\pkg{iNZight} is a \\gls{gui}-based tool written in R that enables both students and researchers to interact with and explore data without the need for code. The tool is designed to be easy to use, with intuitive controls and clever defaults for common tasks. \\pkg{iNZight} also provides more complex features for manipulation and analysis of data, and includes some code-writing capabilities for researchers to efficiently generate reproducible outputs, or as a pathway for newcomers to learn the basics of the \\proglang{R} programming environment."
