on:
  push
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

name: Compile papers

jobs:
  compile-papers:
    runs-on: ubuntu-20.04
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install system dependencies
        run: |
          sudo apt-get install \
            poppler-utils libxml2-dev libnlopt-dev libcurl4-openssl-dev \
            libmagick++-dev libudunits2-dev
      - name: Query dependencies
        run: Rscript get_deps.R .github/depends.Rds
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-2-
      - name: Install dependencies
        run: Rscript get_deps.R
      - name: Build
        env:
          TZ: "Pacific/Auckland"
        run: Rscript build_papers.R
      - name: Render README
        run: Rscript -e "rmarkdown::render('README.Rmd')"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add **/*.pdf figure/* README.md || echo "Nothing to add"
          git commit -m "Compile PDFs and update README" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
