on: push
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

name: Compile papers

jobs:
  compile-papers:
    runs-on: ubuntu-20.04
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install system dependencies
        run: sudo apt-get install poppler-utils texlive-binaries scrot libgtk2.0-dev xorg-dev libxml2-dev libnlopt-dev libcurl4-openssl-dev
      - name: Query dependencies
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: Rscript get_deps.R .github/depends.Rds
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-1-
      - name: Install dependencies
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: Rscript get_deps.R
      - name: Build
        uses: GabrielBB/xvfb-action@v1.0
        env:
          TZ: 'Pacific/Auckland'
        with:
          run: Rscript build_papers.R
      - name: Install rmarkdown
        run: |
          install.packages("remotes")
          remotes::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Render README
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add **/*.pdf figure/* README.md
          git commit -m "Compile PDFs and update README" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
